apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: nodejs-template
  title: Example Nodejs Template
  description: Este é um exemplo de nodejs service
  tags:
    - nodejs

spec:
  owner: core
  type: service
  parameters:
    - title: Configuração do projeto
      required:
        - name
        - title
        - description
        - namespace
      properties:
        name:
          title: Name
          type: string
          description: Nome do projeto
          ui:autofocus: true
        title:
          title: Title
          type: string
          description: nome do projeto que sera exibido no readme etc..
        description:
          title: Description
          type: string
          description: Descrição do projeto
          ui:options:
            rows: 5
        namespace:
          title: Namespace
          type: string
          description: Namespace onde sera aplicado o projeto no K8S
        Owner:
          title: Owner
          type: string
          description: Time responsavel do projeto
          ui:field: OwnerPicker
          ui:options:
            allowedKinds: [Group]
    - title: Escolher o Repository
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  # These steps are executed in the scaffolder backend, using data that we gathered
  # via the parameters above.
  steps:
    # Each step executes an action, in this case one templates files into the working directory.
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          title: ${{ parameters.title }}
          namespace: ${{ parameters.namespace }}

    # This step publishes the contents of the working directory to GitHub.
    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
